# meta.yaml - package specification for rmgmolecule subpackage
package:
  name: rmgmolecule
  version: 1.0.0

source:
  path: ../

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cairo
    - cairocffi
    - cython >=0.25.2
    - lpsolve55
    - numpy
    - openbabel >=3
    - pydot
    - pyrdl
    - python==3.7
    - quantities
    - rdkit >=2018
  run:
    - cairo
    - cairocffi
    - cython >=0.25.2
    - lpsolve55
    - numpy
    - openbabel >=3
    - pydot
    - pyrdl
    - python==3.7
    - quantities
    - rdkit >=2018
test:
  imports:
    - rmgpy.molecule
  commands:
    - python -c 'from rmgpy.molecule import Molecule; mol=Molecule().from_smiles("CC")'

about:
  home: https://github.com/ReactionMechanismGenerator/RMG-Py
  license: MIT
  summary: "The ReactionMechanismGenerator Molecule Subpackage"