# For conda build
package:
  name: rmg
  version: 3.2.0

source:
  path: ../

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - conda-forge::libxcrypt  # remove after upgrading Python versions
    - conda-forge::cairo
    - conda-forge::cairocffi
    - conda-forge::ffmpeg
    - conda-forge::xlrd
    - conda-forge::xlwt
    - conda-forge::h5py
    - conda-forge::graphviz
    - conda-forge::markupsafe
    - conda-forge::psutil
    - conda-forge::ncurses
    - conda-forge::suitesparse
    - conda-forge::coolprop
    - cantera::cantera =2.6
    - conda-forge::mopac
    - conda-forge::cclib >=1.6.3,!=1.8.0
    - conda-forge::openbabel >=3
    - conda-forge::rdkit >=2022.09.1
    - conda-forge::python >=3.7
    - conda-forge::coverage
    - conda-forge::cython >=0.25.2
    - conda-forge::scikit-learn
    - conda-forge::scipy <1.11
    - conda-forge::numpy >=1.10.0
    - conda-forge::pydot
    - conda-forge::jinja2
    - conda-forge::jupyter
    - conda-forge::pymongo
    - conda-forge::pyparsing
    - conda-forge::pyyaml
    - conda-forge::networkx
    - conda-forge::pytest
    - conda-forge::pytest-cov
    - conda-forge::matplotlib >=1.5
    - conda-forge::mpmath
    - conda-forge::pandas
    - conda-forge::gprof2dot
    - conda-forge::numdifftools
    - conda-forge::quantities
    - rmg::lpsolve55
    - rmg::muq2
    - rmg::pydas >=1.0.3
    - rmg::pydqed >=1.0.3
    - rmg::pyrdl
    - rmg::symmetry
    - conda-forge::nomkl
  run:
    - conda-forge::libxcrypt  # remove after upgrading Python versions
    - jacksonburns::rmgdatabase
    - conda-forge::cairo
    - conda-forge::cairocffi
    - conda-forge::ffmpeg
    - conda-forge::xlrd
    - conda-forge::xlwt
    - conda-forge::h5py
    - conda-forge::graphviz
    - conda-forge::markupsafe
    - conda-forge::psutil
    - conda-forge::ncurses
    - conda-forge::suitesparse
    - conda-forge::coolprop
    - cantera::cantera =2.6
    - conda-forge::mopac
    - conda-forge::cclib >=1.6.3,!=1.8.0
    - conda-forge::openbabel >=3
    - conda-forge::rdkit >=2022.09.1
    - conda-forge::python >=3.7
    - conda-forge::coverage
    - conda-forge::cython >=0.25.2
    - conda-forge::scikit-learn
    - conda-forge::scipy <1.11
    - conda-forge::numpy >=1.10.0
    - conda-forge::pydot
    - conda-forge::jinja2
    - conda-forge::jupyter
    - conda-forge::pymongo
    - conda-forge::pyparsing
    - conda-forge::pyyaml
    - conda-forge::networkx
    - conda-forge::pytest
    - conda-forge::pytest-cov
    - conda-forge::matplotlib >=1.5
    - conda-forge::mpmath
    - conda-forge::pandas
    - conda-forge::gprof2dot
    - conda-forge::numdifftools
    - conda-forge::quantities
    - rmg::lpsolve55
    - rmg::muq2
    - rmg::pydas >=1.0.3
    - rmg::pydqed >=1.0.3
    - rmg::pyrdl
    - rmg::symmetry
    - conda-forge::nomkl
test:
  requires:
    - conda-forge::libxcrypt  # remove after upgrading Python versions
    - jacksonburns::rmgdatabase
    - conda-forge::cairo
    - conda-forge::cairocffi
    - conda-forge::ffmpeg
    - conda-forge::xlrd
    - conda-forge::xlwt
    - conda-forge::h5py
    - conda-forge::graphviz
    - conda-forge::markupsafe
    - conda-forge::psutil
    - conda-forge::ncurses
    - conda-forge::suitesparse
    - conda-forge::coolprop
    - cantera::cantera =2.6
    - conda-forge::mopac
    - conda-forge::cclib >=1.6.3,!=1.8.0
    - conda-forge::openbabel >=3
    - conda-forge::rdkit >=2022.09.1
    - conda-forge::python >=3.7
    - conda-forge::coverage
    - conda-forge::cython >=0.25.2
    - conda-forge::scikit-learn
    - conda-forge::scipy <1.11
    - conda-forge::numpy >=1.10.0
    - conda-forge::pydot
    - conda-forge::jinja2
    - conda-forge::jupyter
    - conda-forge::pymongo
    - conda-forge::pyparsing
    - conda-forge::pyyaml
    - conda-forge::networkx
    - conda-forge::pytest
    - conda-forge::pytest-cov
    - conda-forge::matplotlib >=1.5
    - conda-forge::mpmath
    - conda-forge::pandas
    - conda-forge::gprof2dot
    - conda-forge::numdifftools
    - conda-forge::quantities
    - rmg::lpsolve55
    - rmg::muq2
    - rmg::pydas >=1.0.3
    - rmg::pydqed >=1.0.3
    - rmg::pyrdl
    - rmg::symmetry
    - conda-forge::nomkl
  source_files:
    - 'examples/rmg/superminimal'
    - 'examples/arkane/networks/n-butanol'
  imports:
    - rmgpy
    - arkane
  commands:
    - rmg.py examples/rmg/superminimal/input.py
    - Arkane.py examples/arkane/networks/n-butanol/input.py

about:
  home: https://github.com/ReactionMechanismGenerator/RMG-Py
  license: MIT
  summary: "A program for automatically generating kinetic models of chemical reaction mechanisms."
